<<<<<<< HEAD
=======
#server:
#  port:8085
#elasticjob:
#  regCenter:
#    serverLists: 127.0.0.1:2181
#    namespace: elasticjob-test	
>>>>>>> db94a56533e8f7f07c54caa0003ef8cb8c76d983
schedulerx:
  jobs: #定义四个定时任务
    simpleJob: # 定义一个单机任务，simpleJob不是任务类型，是任务名称，可以随意替换
      elasticJobClass: com.alibaba.schedulerx.example.elasticjob.job.MySimpleJob
      cron: 0/30 * * * * ?
      shardingTotalCount: 1
      overwrite: true
    simpleJob2: # 定义一个单机任务，simpleJob2不是任务类型，是任务名称，可以随意替换
      elasticJobClass: com.alibaba.schedulerx.example.elasticjob.job.MySimpleJob
      cron: 0/30 * * * * ?
      shardingTotalCount: 1
      overwrite: true
    shardingJob: # 定义一个分片任务，shardingJob不是任务类型，是任务名称，可以随意替换
      elasticJobClass: com.alibaba.schedulerx.example.elasticjob.job.MyShardingJob
      cron: 0 * * * * ?
      shardingTotalCount: 3
      shardingItemParameters: 0=Beijing,1=Shanghai,2=Guangzhou
      overwrite: true
    dataflowJob: # 定义一个流式任务，dataflowJob不是任务类型，是任务名称，可以随意替换
      elasticJobClass: com.alibaba.schedulerx.example.elasticjob.job.MyDataFlowJob
      cron: 0 * * * * ?
      shardingTotalCount: 3
      shardingItemParameters: 0=Beijing,1=Shanghai,2=Guangzhou
      props.streaming.process: true
      overwrite: true
  
spring:
   schedulerx2:
      endpoint: acm.aliyun.com
      namespace: 433d8b23-xxxx-xxxx-xxxx-90d4d1b9a4af
      groupId: xxxxxxx
      appKey: xxxxxxxxxxxxxxx
      regionId: public
      aliyunAccessKey: xxxxxxxxxxxxx
      aliyunSecretKey: xxxxxxxxxxxxx