dubbo.scan.basePackages=com.alibaba.edas
dubbo.application.name=dubbo-provider-demo
dubbo.registry.address=nacos://127.0.0.1:8848
dubbo.provider.port=20220
server.port=8088
spring.cloud.nacos.config.import-check.enabled=false
spring.config.import=optional:nacos:dubbo-provider-demo.properties
