apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-spec: slb.s1.small
  name: {{ .Values.apps.serviceName }}
  namespace: {{ .Values.apps.namespace }}
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Local
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - nodePort: 30830
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    edas.alibabacloud.com/app: consumer
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
