server:
  port: 28084
spring:
  application:
    name: rocketmq-broadcast-consumer1-example
  cloud:
    stream:
      function:
        definition: consumer;
      rocketmq:
        binder:
          name-server: http://MQ_INST_1036052989950239_BcL89CHg.cn-shanghai.mq-internal.aliyuncs.com:8080
        bindings:
          producer-out-0:
            producer:
              access-key: ${access-key}
              secret-key: ${secret-key}
              group: GID_producer
          consumer-in-0:
            consumer:
              access-key: ${access-key}
              secret-key: ${secret-key}
              ## According to the configured number of `max-reconsume-times`,
              ## the server will re-push the message according to whether the client's consumption is successful or not
              push:
                max-reconsume-times: 3
      bindings:
        producer-out-0:
          destination: retrieable
        consumer-in-0:
          destination: retrieable
          group: GID_producer
logging:
  level:
    org.springframework.context.support: debug

rocketmq:
  access-key: ${access-key}
  secret-key: ${secret-key}

#dubbo:
#  application:
#    name: dubbo-springboot3
#  protocol:
#    name: dubbo
#    port: -1

